In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy as scipy

In [4]:
df=pd.read_csv('2022-property-sales-data-1.csv')
pd.set_option('display.max.rows', None) #Show all columns in header
df.head()

,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,98461,Manufacturing,30131000,NaN,9,6300,Service Building,Concrete Block,1.0,1978.0,NaN,20600.0,6,NaN,0,0,0,2022-04-01,950000
1,98464,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07,385000
2,98508,Residential,49980110,NaN,9,40,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,1341648,2022-01-07,800000
3,98519,Residential,49993200,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1959.0,6.0,1334.0,1,3.0,1,1,83200,2022-08-09,280000
4,98561,Residential,50042000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1980.0,10.0,1006.0,1,6.0,1,0,8303,2022-05-23,233100

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7146 entries, 0 to 7145
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PropertyID    7146 non-null   int64
 1   PropType      7146 non-null   object
 2   taxkey        7146 non-null   int64
 3   CondoProject  885 non-null    object
 4   District      7146 non-null   int64
 5   nbhd          7146 non-null   int64
 6   Style         7125 non-null   object
 7   Extwall       6220 non-null   object
 8   Stories       7107 non-null   float64
 9   Year_Built    7135 non-null   float64
 10  Rooms         6703 non-null   float64
 11  FinishedSqft  7122 non-null   float64
 12  Units         7146 non-null   int64
 13  Bdrms         6703 non-null   float64
 14  Fbath         7146 non-null   int64
 15  Hbath         7146 non-null   int64
 16  Lotsize       7146 non-null   int64
 17  Sale_date     7146 non-null   object
 18  Sale_price    7146 non-null   int64
dtypes: float64(5), int64(9), object(5)
memory usage: 1.0+ MB

In [6]:
df.shape

(7146, 19)

In [12]:
df.tail()

,PropertyID,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
7141,260642,Condominium,7160339000,1912 W SALEM ST,COLLEGE HEIGHTS,13,5360,Low Rise 1-3 Stories,NaN,2.0,1974.0,10.0,1100.0,1,4.0,1,1,1,2022-03-11,125900.0
7142,260654,Condominium,7160351000,6316 S 20TH ST,COLLEGE HEIGHTS,13,5360,Low Rise 1-3 Stories,NaN,1.0,1974.0,5.0,1379.0,1,2.0,1,1,1,2022-10-28,150000.0
7143,260668,Condominium,7160365000,6376 S 20TH ST,COLLEGE HEIGHTS,13,5360,Low Rise 1-3 Stories,NaN,2.0,1974.0,10.0,1100.0,1,4.0,1,1,1,2022-03-15,130000.0
7144,260669,Condominium,7160366000,6378 S 20TH ST,COLLEGE HEIGHTS,13,5360,Low Rise 1-3 Stories,NaN,2.0,1974.0,5.0,1100.0,1,2.0,1,1,1,2022-12-30,123000.0
7145,260678,Condominium,7160375000,6354 S 20TH ST,COLLEGE HEIGHTS,13,5360,Low Rise 1-3 Stories,NaN,1.0,1974.0,5.0,1141.0,1,2.0,1,1,1,2022-07-08,157500.0

In [3]:
df['Year_Built'].head(20)

0     1978.0
1     1982.0
2        NaN
3     1959.0
4     1980.0
5     1982.0
6     1984.0
7     2007.0
8     1973.0
9     1973.0
10    1973.0
11    1973.0
12    1973.0
13    1973.0
14    1973.0
15    1973.0
16    1973.0
17    1973.0
18    1973.0
19    1973.0
Name: Year_Built, dtype: float64

In [3]:
#df.loc['5360']
#Key Error, should not use str for loc here

In [5]:
df.iloc[9]

PropertyID                     98715
PropType                 Condominium
taxkey                      70036000
CondoProject    NORTHRIDGE WOOD LAKE
District                           9
nbhd                            5010
Style                Condo Townhouse
Extwall                          NaN
Stories                          2.0
Year_Built                    1973.0
Rooms                            7.0
FinishedSqft                  1437.0
Units                              1
Bdrms                            4.0
Fbath                              2
Hbath                              1
Lotsize                            0
Sale_date                 2022-04-14
Sale_price                    123000
Name: 9, dtype: object

In [4]:
df[df['District'] <3].head(15)

,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
282,104069,Residential,1020017100,NaN,1,380,Cape Cod,Brick,1.0,1948.0,5.0,1248.0,1,3.0,1,0,9350,2022-03-18,204000
283,104098,Residential,1020050110,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1963.0,6.0,1159.0,1,3.0,2,0,7540,2022-10-24,280000
284,104108,Residential,1020108000,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1952.0,14.0,1120.0,1,8.0,2,0,10800,2022-04-11,240000
285,104112,Residential,1020112000,NaN,1,380,Colonial,Wood,2.0,1966.0,16.0,1520.0,1,8.0,1,1,10895,2022-02-28,165000
286,104116,Residential,1020116000,NaN,1,380,Cape Cod,Aluminum/Vinyl,1.5,1957.0,12.0,1678.0,1,6.0,1,1,13044,2022-02-11,251660
287,104123,Residential,1020123000,NaN,1,380,Ranch,Wood,1.0,1955.0,5.0,1120.0,1,3.0,1,1,11850,2022-08-05,250000
288,104126,Residential,1020126000,NaN,1,380,Ranch,Brick,1.0,1956.0,5.0,1483.0,1,3.0,2,0,12000,2022-06-07,299900
289,104133,Residential,1020133000,NaN,1,380,Ranch,Brick,1.0,1955.0,5.0,923.0,1,3.0,2,0,11175,2022-08-04,180000
290,104136,Residential,1020136000,NaN,1,380,Ranch,Brick,1.0,1955.0,12.0,1261.0,1,6.0,2,0,11138,2022-04-12,205000
291,104142,Residential,1020142000,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1960.0,5.0,1186.0,1,3.0,1,1,11132,2022-07-05,207500
292,104149,Residential,1020206000,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1963.0,5.0,1255.0,1,3.0,2,1,11840,2022-07-26,195000
293,104159,Residential,1020216000,NaN,1,380,Ranch,Brick,1.0,1960.0,5.0,1211.0,1,3.0,1,1,12348,2022-06-22,140000
294,104166,Residential,1020223000,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1964.0,6.0,1164.0,1,3.0,1,1,11310,2022-03-18,210000
295,104240,Residential,1020579000,NaN,1,380,Ranch,Aluminum/Vinyl,1.0,1982.0,10.0,1007.0,1,6.0,1,1,8701,2022-02-16,190000
296,104334,Commercial,1029970100,NaN,1,6216,Pole Building,Metal Siding,1.0,1984.0,0.0,3908.0,2,4.0,0,0,11792,2022-06-09,215000

In [7]:
specific_extwalls=['Wood','Brick']
df[df['Extwall'].isin(specific_extwalls)][0:15]

,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
1,98464,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07,385000
138,101451,Commercial,449972100,NaN,9,6465,Funeral Home,Brick,1.0,1976.0,NaN,10153.0,1,NaN,0,0,0,2022-12-21,1089587
197,102612,Residential,740242000,NaN,9,240,Colonial,Wood,2.0,2002.0,18.0,2450.0,1,6.0,2,1,13092,2022-04-28,415000
200,102654,Residential,749982220,NaN,9,240,Tudor,Brick,1.0,1928.0,7.0,1866.0,1,3.0,3,0,23958,2022-08-18,290000
203,102688,Commercial,760101000,NaN,5,6453,Office Building - 1 Story,Brick,1.0,1994.0,NaN,30000.0,1,NaN,0,0,0,2022-12-29,1725000
205,102708,Commercial,770091100,NaN,5,6453,Office Building - Multi Story ( Ofc & Apt),Brick,3.0,1990.0,NaN,245266.0,8,NaN,0,0,788775,2022-08-26,20828000
210,102804,Residential,789992221,NaN,9,240,Ranch,Wood,1.0,1963.0,12.0,2557.0,1,6.0,2,1,23650,2022-07-01,330000
224,102993,Residential,810043000,NaN,9,240,Ranch,Wood,1.0,1958.0,5.0,1001.0,1,3.0,1,1,22500,2022-06-09,195000
228,103065,Residential,819990000,NaN,9,240,Ranch,Brick,1.0,1950.0,7.0,2104.0,1,3.0,1,1,209524,2022-09-13,200000
256,103661,Residential,840009000,NaN,9,360,Ranch,Wood,1.0,1958.0,6.0,1154.0,1,3.0,1,0,12600,2022-10-21,165000
258,103676,Residential,840024000,NaN,9,360,Ranch,Brick,1.0,1957.0,5.0,1053.0,1,3.0,1,0,10000,2022-08-10,223000
260,103718,Residential,840066000,NaN,9,360,Ranch,Wood,1.0,1957.0,5.0,1099.0,1,3.0,2,0,10000,2022-10-24,200000
265,103811,Residential,840159000,NaN,9,360,Ranch,Wood,1.0,1957.0,7.0,1547.0,1,3.0,1,1,11376,2022-07-21,225000
270,103828,Residential,840176000,NaN,9,360,Ranch,Brick,1.0,1957.0,10.0,1140.0,1,6.0,1,0,10473,2022-04-05,230000
271,103841,Residential,840189000,NaN,9,360,Ranch,Wood,1.0,1957.0,6.0,1155.0,1,3.0,1,1,11314,2022-11-15,234500

In [6]:
df[df['Extwall'].str.contains('Wood|Brick', regex=True,na=False)].head(15)
#specify NaN as false so not mess up data.

,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
1,98464,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07,385000
138,101451,Commercial,449972100,NaN,9,6465,Funeral Home,Brick,1.0,1976.0,NaN,10153.0,1,NaN,0,0,0,2022-12-21,1089587
193,102594,Lg Apartment,740196000,NaN,9,6970,Subsidized Apartments,Brick on Frame,2.0,1979.0,NaN,61204.0,56,NaN,0,0,154159,2022-03-17,3000000
197,102612,Residential,740242000,NaN,9,240,Colonial,Wood,2.0,2002.0,18.0,2450.0,1,6.0,2,1,13092,2022-04-28,415000
200,102654,Residential,749982220,NaN,9,240,Tudor,Brick,1.0,1928.0,7.0,1866.0,1,3.0,3,0,23958,2022-08-18,290000
203,102688,Commercial,760101000,NaN,5,6453,Office Building - 1 Story,Brick,1.0,1994.0,NaN,30000.0,1,NaN,0,0,0,2022-12-29,1725000
205,102708,Commercial,770091100,NaN,5,6453,Office Building - Multi Story ( Ofc & Apt),Brick,3.0,1990.0,NaN,245266.0,8,NaN,0,0,788775,2022-08-26,20828000
210,102804,Residential,789992221,NaN,9,240,Ranch,Wood,1.0,1963.0,12.0,2557.0,1,6.0,2,1,23650,2022-07-01,330000
224,102993,Residential,810043000,NaN,9,240,Ranch,Wood,1.0,1958.0,5.0,1001.0,1,3.0,1,1,22500,2022-06-09,195000
228,103065,Residential,819990000,NaN,9,240,Ranch,Brick,1.0,1950.0,7.0,2104.0,1,3.0,1,1,209524,2022-09-13,200000
256,103661,Residential,840009000,NaN,9,360,Ranch,Wood,1.0,1958.0,6.0,1154.0,1,3.0,1,0,12600,2022-10-21,165000
258,103676,Residential,840024000,NaN,9,360,Ranch,Brick,1.0,1957.0,5.0,1053.0,1,3.0,1,0,10000,2022-08-10,223000
260,103718,Residential,840066000,NaN,9,360,Ranch,Wood,1.0,1957.0,5.0,1099.0,1,3.0,2,0,10000,2022-10-24,200000
265,103811,Residential,840159000,NaN,9,360,Ranch,Wood,1.0,1957.0,7.0,1547.0,1,3.0,1,1,11376,2022-07-21,225000
270,103828,Residential,840176000,NaN,9,360,Ranch,Brick,1.0,1957.0,10.0,1140.0,1,6.0,1,0,10473,2022-04-05,230000

In [8]:
df = df.reset_index()

In [9]:
df1=df.set_index('PropertyID')
df1.head()

,index,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
PropertyID,,,,,,,,,,,,,,,,,,,
98461,0,Manufacturing,30131000,NaN,9,6300,Service Building,Concrete Block,1.0,1978.0,NaN,20600.0,6,NaN,0,0,0,2022-04-01,950000
98464,1,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07,385000
98508,2,Residential,49980110,NaN,9,40,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,1341648,2022-01-07,800000
98519,3,Residential,49993200,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1959.0,6.0,1334.0,1,3.0,1,1,83200,2022-08-09,280000
98561,4,Residential,50042000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1980.0,10.0,1006.0,1,6.0,1,0,8303,2022-05-23,233100

In [7]:
#Filtering Columns and Rows in Pandas | Python Pandas Tutorials at 5:10

In [10]:
df1.filter(items=['PropType','taxkey'], axis=1)[0:10]
#axis 0 not work

                 PropType    taxkey
PropertyID
98461       Manufacturing  30131000
98464          Commercial  30152000
98508         Residential  49980110
98519         Residential  49993200
98561         Residential  50042000
98593         Residential  50074000
98604         Residential  50085000
98608         Residential  50089000
98696         Condominium  70017000
98715         Condominium  70036000

In [13]:
#df1.filter(items=[98784],axis=1).head()
#not working

In [10]:
#Find duplicate PropertyID
df[df1.index.duplicated()].head(10)

,index,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
21,21,98868,Condominium,310253000,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,4.0,1295.0,1,2.0,1,1,1,2022-12-29,140000
46,46,99593,Condominium,340642000,WOODLANDS,9,5060,Condo Townhouse,NaN,2.5,1970.0,5.0,1054.0,1,3.0,1,1,1,2022-09-29,62500
49,49,99621,Condominium,340670000,WOODLANDS,9,5060,Condo Townhouse,NaN,2.5,1970.0,5.0,1054.0,1,3.0,1,1,1,2022-07-26,28500
51,51,99641,Condominium,340690000,WOODLANDS,9,5060,Condo Townhouse,NaN,2.5,1970.0,5.0,1054.0,1,3.0,1,1,1,2022-03-17,48000
56,56,99765,Condominium,340814000,WOODLANDS,9,5060,Condo Townhouse,NaN,2.5,1970.0,5.0,1054.0,1,3.0,1,1,1,2022-11-30,25000
68,68,100024,Residential,341258000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1950.0,8.0,923.0,1,6.0,1,0,7449,2022-10-05,175000
104,104,100819,Condominium,430352000,SERVITE WOODS (ATRIUM),9,5070,Low Rise 1-3 Stories,NaN,1.0,1974.0,10.0,1024.0,1,4.0,2,0,1,2022-05-27,69900
128,128,101136,Condominium,440069000,WHISPERING HILLS (WALK-UP),9,5080,Condo BI/TRI Level,NaN,1.0,1972.0,4.0,896.0,1,2.0,1,1,1,2022-12-16,60000
202,202,102657,Residential,749983100,NaN,9,240,Colonial,Stone,2.0,1855.0,6.0,1846.0,1,4.0,2,1,40511,2022-11-23,300000
231,231,103191,Condominium,830234000,HEATHERS,9,5110,Condo Townhouse,NaN,2.0,1970.0,4.0,1056.0,1,2.0,1,2,1,2022-07-21,47000

In [69]:
df1.filter(like='988',axis=0)

,index,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
PropertyID,,,,,,,,,,,,,,,,,,,,
98852,19,Condominium,310237000,8991 N 70TH ST,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,6.0,1401.0,1,3.0,2,1,1,2022-04-13,153000.0
98868,20,Condominium,310253000,9025 N 70TH ST,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,4.0,1295.0,1,2.0,1,1,1,2022-10-14,80000.0
98868,21,Condominium,310253000,9025 N 70TH ST,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,4.0,1295.0,1,2.0,1,1,1,2022-12-29,140000.0
98875,22,Condominium,310260000,9039 N 70TH ST,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,6.0,1401.0,1,3.0,2,1,1,2022-11-16,137000.0
99881,61,Condominium,341072000,"9011 N SWAN RD, Unit k",WOODLANDS,9,5060,Condo Townhouse,NaN,2.5,1970.0,5.0,1054.0,1,3.0,1,1,1,2022-07-21,46000.0
109888,516,Residential,1430664000,8009 W KIEHNAU AV,NaN,9,480,Ranch,Aluminum/Vinyl,1.0,1958.0,5.0,1133.0,1,3.0,1,1,7200,2022-08-11,170000.0
139881,1951,Residential,2500034000,4115 N 63RD ST,NaN,2,1490,Ranch,Aluminum/Vinyl,1.0,1955.0,5.0,1278.0,1,3.0,1,1,5330,2022-06-29,193000.0
159988,2772,Residential,2890702000,3291-3293 N 58TH ST,NaN,10,1850,Duplex N/S,Brick,2.0,1946.0,12.0,2627.0,2,5.0,2,0,5200,2022-10-03,215000.0
182988,3814,Residential,3460202000,2139 N 58TH ST,NaN,10,2540,Milwaukee Bungalow,Wood,1.0,1922.0,20.0,2201.0,1,14.0,2,0,5950,2022-02-25,260000.0
198804,4483,Residential,3901145000,1903 W HIGHLAND AV,NaN,4,3040,Colonial,Wood,2.0,1982.0,7.0,1222.0,1,4.0,1,1,8100,2022-02-23,140000.0
198872,4484,Lg Apartment,3901331000,1517 W KILBOURN AV,NaN,4,6977,Rooming House - 8 or more units,Precast Masonary,NaN,2016.0,NaN,9960.0,22,NaN,0,0,4770,2022-02-25,1712500.0
199887,4541,Condominium,3930212100,"929 N ASTOR ST, Unit 304",REGENCY HOUSE,4,5990,High Rise > 12 Stories,NaN,1.0,1968.0,3.0,819.0,1,1.0,1,1,0,2022-06-24,225000.0
207988,4938,Residential,4310402100,1328 S 4TH ST,NaN,12,4020,Res O/S A & 1/2,Aluminum/Vinyl,1.0,1885.0,7.0,1381.0,1,4.0,1,0,6250,2022-04-19,180000.0
217988,5291,Residential,4689950000,1151 W WINDLAKE AV,NaN,12,4120,Res O/S 2sty +,Brick,2.0,1923.0,8.0,3371.0,1,5.0,2,1,5400,2022-04-27,275000.0
229880,5758,Residential,5070518000,1202 W DAKOTA ST,NaN,14,4180,Duplex O/S,Aluminum/Vinyl,1.5,1920.0,9.0,1672.0,2,4.0,2,0,8280,2022-07-07,195000.0
229882,5759,Residential,5070520000,2857 S 12TH ST,NaN,14,4180,Res O/S A & 1/2,Aluminum/Vinyl,1.0,1923.0,5.0,1382.0,1,3.0,2,0,4270,2022-02-04,88000.0
239881,6205,Residential,5360274000,3332 S 8TH ST,NaN,14,4520,Duplex O/S,Aluminum/Vinyl,1.0,1916.0,8.0,1382.0,2,3.0,2,1,3660,2022-09-12,240000.0
244988,6435,Residential,5490142000,166 W TRIPOLI AV,NaN,13,4620,Ranch,Aluminum/Vinyl,1.0,1937.0,4.0,757.0,1,2.0,1,0,5460,2022-05-06,175000.0
245988,6487,Residential,5510821000,3712 S 15TH ST,NaN,13,4520,Ranch,Aluminum/Vinyl,1.0,1946.0,8.0,679.0,1,4.0,1,0,5160,2022-02-04,152500.0
253988,6850,Residential,5940168000,4387 S PINE AV,NaN,13,4720,Cape Cod,Aluminum/Vinyl,1.5,1941.0,6.0,1098.0,1,3.0,1,0,5940,2022-06-17,210000.0

In [55]:
df1.loc[239859]
#loc is label based, iloc is integer based

index                      6203
PropType            Residential
taxkey               5360251000
Address           3210 S 8TH ST
CondoProject                NaN
District                     14
nbhd                       4520
Style           Res O/S A & 1/2
Extwall               Prem Wood
Stories                     1.0
Year_Built               1918.0
Rooms                       5.0
FinishedSqft             1428.0
Units                         1
Bdrms                       2.0
Fbath                         1
Hbath                         0
Lotsize                    5490
Sale_date            2022-07-22
Sale_price             217000.0
Name: 239859, dtype: object

In [50]:
print(df1.index)

Index([ 98461,  98464,  98508,  98519,  98561,  98593,  98604,  98608,  98696,
        98715,
       ...
       260546, 260559, 260584, 260588, 260630, 260642, 260654, 260668, 260669,
       260678],
      dtype='int64', name='PropertyID', length=7146)

In [61]:
df1.iloc[6203]

index                      6203
PropType            Residential
taxkey               5360251000
Address           3210 S 8TH ST
CondoProject                NaN
District                     14
nbhd                       4520
Style           Res O/S A & 1/2
Extwall               Prem Wood
Stories                     1.0
Year_Built               1918.0
Rooms                       5.0
FinishedSqft             1428.0
Units                         1
Bdrms                       2.0
Fbath                         1
Hbath                         0
Lotsize                    5490
Sale_date            2022-07-22
Sale_price             217000.0
Name: 239859, dtype: object

In [15]:
df[df['Year_Built']<1960].sort_values(by=['Year_Built','Style'], ascending=[True,False]).head(15)

,PropertyID,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
4881,207059,Commercial,4280278000,NaN,12,6275,Parking Lot,NaN,0.0,0.0,NaN,0.0,19,NaN,0,0,0,2022-06-30,50000
6274,241422,Commercial,5381410000,NaN,14,6282,Parking Lot,NaN,0.0,0.0,NaN,0.0,0,NaN,0,0,0,2022-01-10,215000
630,265047,Commercial,1529951110,NaN,2,6212,Commercial Land,NaN,0.0,0.0,NaN,0.0,0,NaN,0,0,30600,2022-05-04,175000
180,261051,Residential,730653000,NaN,9,240,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,24910,2022-03-31,20000
320,104919,Residential,1090132200,NaN,5,440,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,87120,2022-10-19,145000
329,105063,Residential,1100432000,NaN,5,440,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,47158,2022-05-31,37500
2132,143109,Residential,2611390000,NaN,5,2100,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,9120,2022-05-20,25000
3144,165541,Residential,3060151000,NaN,10,1860,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,3880,2022-07-14,10000
3244,167839,Residential,3080816000,NaN,15,1780,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,4800,2022-12-02,7000
3276,168844,Residential,3100309000,NaN,7,2950,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,3750,2022-05-25,4000
4004,188450,Residential,3531762000,NaN,6,2970,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,5572,2022-03-15,26000
4394,196143,Residential,3661983000,NaN,15,2380,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,4945,2022-02-28,9000
4949,208213,Residential,4311093000,NaN,12,4020,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,7000,2022-10-13,105000
5173,214512,Residential,4601009000,NaN,12,4100,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,1770,2022-08-04,5000
5181,214780,Residential,4601464000,NaN,12,4100,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN,0,0,1440,2022-09-14,21000

In [11]:
df2=df.set_index(['PropertyID','Sale_price'])
df2.head(10)

,,index,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date
PropertyID,Sale_price,,,,,,,,,,,,,,,,,,
98461,950000,0,Manufacturing,30131000,NaN,9,6300,Service Building,Concrete Block,1.0,1978.0,NaN,20600.0,6,NaN,0,0,0,2022-04-01
98464,385000,1,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07
98508,800000,2,Residential,49980110,NaN,9,40,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,1341648,2022-01-07
98519,280000,3,Residential,49993200,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1959.0,6.0,1334.0,1,3.0,1,1,83200,2022-08-09
98561,233100,4,Residential,50042000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1980.0,10.0,1006.0,1,6.0,1,0,8303,2022-05-23
98593,215000,5,Residential,50074000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1982.0,5.0,1007.0,1,3.0,1,0,7200,2022-07-25
98604,150000,6,Residential,50085000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1984.0,5.0,1301.0,1,3.0,2,0,7200,2022-03-29
98608,400000,7,Residential,50089000,NaN,9,40,Colonial,Aluminum/Vinyl,2.0,2007.0,9.0,2237.0,1,4.0,2,1,15677,2022-05-10
98696,122000,8,Condominium,70017000,NORTHRIDGE WOOD LAKE,9,5010,Condo Townhouse,NaN,2.0,1973.0,7.0,1437.0,1,3.0,2,1,0,2022-05-16
98715,123000,9,Condominium,70036000,NORTHRIDGE WOOD LAKE,9,5010,Condo Townhouse,NaN,2.0,1973.0,7.0,1437.0,1,4.0,2,1,0,2022-04-14

In [12]:
df2.reset_index(inplace=True)
df2.head()

,PropertyID,Sale_price,index,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date
0,98461,950000,0,Manufacturing,30131000,NaN,9,6300,Service Building,Concrete Block,1.0,1978.0,NaN,20600.0,6,NaN,0,0,0,2022-04-01
1,98464,385000,1,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07
2,98508,800000,2,Residential,49980110,NaN,9,40,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,1341648,2022-01-07
3,98519,280000,3,Residential,49993200,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1959.0,6.0,1334.0,1,3.0,1,1,83200,2022-08-09
4,98561,233100,4,Residential,50042000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1980.0,10.0,1006.0,1,6.0,1,0,8303,2022-05-23

In [19]:
df[df2.index.duplicated()]
#Checking to see if there are any rows with the same index values

Empty DataFrame
Columns: [index, PropertyID, PropType, taxkey, CondoProject, District, nbhd, Style, Extwall, Stories, Year_Built, Rooms, FinishedSqft, Units, Bdrms, Fbath, Hbath, Lotsize, Sale_date, Sale_price]
Index: []

In [19]:
#df[df2['PropertyID']=='98868'] , Keyerror
df2.loc[215441,128000.00] #(PropertyID,Sale_price)

PropType        Residential
taxkey           4610723000
CondoProject            NaN
District                 12
nbhd                   4100
Style               Triplex
Extwall                Wood
Stories                 2.0
Year_Built           1900.0
Rooms                  14.0
FinishedSqft         2691.0
Units                     3
Bdrms                   6.0
Fbath                     3
Hbath                     0
Lotsize                2408
Sale_date        2022-01-31
Name: (215441, 128000), dtype: object

In [96]:
df.iloc[5199]

index                            5199
PropertyID                     215441
PropType                  Residential
taxkey                     4610723000
Address         814-816 W WINDLAKE AV
CondoProject                      NaN
District                           12
nbhd                             4100
Style                         Triplex
Extwall                          Wood
Stories                           2.0
Year_Built                     1900.0
Rooms                            14.0
FinishedSqft                   2691.0
Units                               3
Bdrms                             6.0
Fbath                               3
Hbath                               0
Lotsize                          2408
Sale_date                  2022-01-31
Sale_price                   128000.0
Name: 5199, dtype: object

In [20]:
pd.options.display.max_rows = 200
df2.sort_index()

,,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date
PropertyID,Sale_price,,,,,,,,,,,,,,,,,
98461,950000,Manufacturing,30131000,NaN,9,6300,Service Building,Concrete Block,1.0,1978.0,NaN,20600.0,6,NaN,0,0,0,2022-04-01
98464,385000,Commercial,30152000,NaN,9,6202,Office Building - 1 Story,Brick,1.0,1982.0,NaN,9688.0,23,NaN,0,0,35719,2022-10-07
98508,800000,Residential,49980110,NaN,9,40,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0,1341648,2022-01-07
98519,280000,Residential,49993200,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1959.0,6.0,1334.0,1,3.0,1,1,83200,2022-08-09
98561,233100,Residential,50042000,NaN,9,40,Ranch,Aluminum/Vinyl,1.0,1980.0,10.0,1006.0,1,6.0,1,0,8303,2022-05-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265996,55000,Commercial,3504061000,NaN,15,6254,Single Tenant Multi Story Retail,Brick,2.0,1905.0,NaN,4414.0,2,NaN,0,0,7205,2022-05-24
266009,1100000,Condominium,3612123100,MODERNE,4,5899,High Rise > 12 Stories,NaN,NaN,2011.0,0.0,2720.0,1,3.0,2,1,0,2022-04-22
266017,1250000,Condominium,3612131110,MODERNE,4,5899,High Rise > 12 Stories,NaN,NaN,2011.0,0.0,3941.0,1,3.0,3,1,0,2022-06-23
266025,200000,Residential,3210527100,NaN,3,2890,Multiple Residential Bldgs,Aluminum/Vinyl,1.0,1900.0,NaN,1588.0,2,NaN,2,0,6399,2022-02-24
266040,86500,Residential,2309987100,NaN,7,1440,Cottage,Aluminum/Vinyl,1.0,1927.0,NaN,686.0,1,NaN,1,0,3816,2022-12-01

In [23]:
df2.loc[98868]
#Just gets value for part 1 of index, PropertyID

,PropType,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date
Sale_price,,,,,,,,,,,,,,,,,
80000,Condominium,310253000,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,4.0,1295.0,1,2.0,1,1,1,2022-10-14
140000,Condominium,310253000,NORTHRIDGE EASTBAY,9,5020,Condo Townhouse,NaN,2.0,1973.0,4.0,1295.0,1,2.0,1,1,1,2022-12-29

In [10]:
df2.iloc[20:22]
#Show how the grouping works with sort index

                       index     PropType     taxkey         Address  \
PropertyID Sale_price
98868      80000.0        20  Condominium  310253000  9025 N 70TH ST
           140000.0       21  Condominium  310253000  9025 N 70TH ST

                             CondoProject  District  nbhd            Style  \
PropertyID Sale_price
98868      80000.0     NORTHRIDGE EASTBAY         9  5020  Condo Townhouse
           140000.0    NORTHRIDGE EASTBAY         9  5020  Condo Townhouse

                      Extwall  Stories  Year_Built  Rooms  FinishedSqft  \
PropertyID Sale_price
98868      80000.0        NaN      2.0      1973.0    4.0        1295.0
           140000.0       NaN      2.0      1973.0    4.0        1295.0

                       Units  Bdrms  Fbath  Hbath  Lotsize   Sale_date
PropertyID Sale_price
98868      80000.0         1    2.0      1      1        1  2022-10-14
           140000.0        1    2.0      1      1        1  2022-12-29

In [13]:
group_by_frame=df.groupby('PropType')

In [14]:
group_by_frame.mean(numeric_only=True)#uses groupby.mean()

,index,PropertyID,taxkey,District,nbhd,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price
PropType,,,,,,,,,,,,,,,
Commercial,3601.758333,186954.504167,3.433022e+09,8.433333,6302.616667,1.636170,1916.481013,0.000000,18308.062500,15.850000,3.597403,0.008333,0.004167,36214.562500,1.422626e+06
Condominium,3485.492672,176507.983089,3.193656e+09,6.351747,5531.869222,1.340856,1967.147689,4.974011,1218.408117,1.000000,2.180791,1.444194,0.369786,0.514092,2.713450e+05
Exempt,1938.000000,139550.000000,2.490008e+09,7.000000,24910.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,2.250000e+05
Lg Apartment,3496.117647,177133.508403,3.432093e+09,6.949580,6751.357143,2.155319,1943.264706,NaN,8398.806723,8.987395,NaN,0.012605,0.000000,10629.382353,8.372885e+05
Manufacturing,1972.333333,141797.333333,2.006806e+09,7.333333,6300.000000,1.000000,1993.666667,NaN,27434.000000,1.666667,NaN,0.000000,0.000000,0.000000,3.181667e+06
Residential,3589.744198,178873.594908,3.515686e+09,8.078455,2730.807066,1.350000,1931.894801,8.246124,1571.580740,1.303083,4.199268,1.553862,0.313474,6319.428992,1.973948e+05

In [27]:
group_by_frame.count()

,PropertyID,taxkey,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
PropType,,,,,,,,,,,,,,,,,,
Commercial,240,240,0,240,240,240,230,235,237,77,240,240,77,240,240,240,240,240
Condominium,887,887,885,887,887,887,0,864,887,885,887,887,885,887,887,887,887,887
Exempt,1,1,0,1,1,1,0,0,0,0,0,1,0,1,1,1,1,1
Lg Apartment,238,238,0,238,238,238,236,235,238,0,238,238,0,238,238,238,238,238
Manufacturing,6,6,0,6,6,6,3,3,3,0,4,6,0,6,6,6,6,6
Residential,5774,5774,0,5774,5774,5753,5751,5770,5770,5741,5753,5774,5741,5774,5774,5774,5774,5774

In [29]:
group_by_frame.min(numeric_only=True)

,PropertyID,taxkey,District,nbhd,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price
PropType,,,,,,,,,,,,,,
Commercial,98464,30152000,1,6202,0.0,0.0,0.0,0.0,0,1.0,0,0,0,25000
Condominium,98696,70017000,2,5010,1.0,1870.0,0.0,325.0,1,0.0,1,0,0,25000
Exempt,139550,2490008100,7,24910,NaN,NaN,NaN,NaN,0,NaN,0,0,0,225000
Lg Apartment,102594,740196000,1,6610,1.0,1880.0,NaN,2400.0,4,NaN,0,0,0,120000
Manufacturing,98461,30131000,1,6300,1.0,1978.0,NaN,0.0,0,NaN,0,0,0,320000
Residential,98508,49980110,1,40,0.0,0.0,0.0,552.0,0,1.0,0,0,0,4000

In [30]:
group_by_frame.max(numeric_only=True)

,PropertyID,taxkey,District,nbhd,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price
PropType,,,,,,,,,,,,,,
Commercial,265996,6909847000,15,6475,12.0,2020.0,0.0,245266.0,737,14.0,2,1,835916,21850000
Condominium,266017,7160375000,15,5999,3.5,2011.0,14.0,6607.0,1,7.0,4,2,1,2625000
Exempt,139550,2490008100,7,24910,NaN,NaN,NaN,NaN,0,NaN,0,0,0,225000
Lg Apartment,265945,6680231000,15,6982,14.0,2018.0,NaN,196753.0,115,NaN,3,0,157732,17400000
Manufacturing,206777,4240321000,9,6300,1.0,2014.0,NaN,68276.0,6,NaN,0,0,0,8025000
Residential,266040,7160283000,15,4920,3.0,2022.0,63.0,7903.0,5,32.0,7,3,1341648,2500000

In [32]:
group_by_frame.sum(numeric_only=True)

,PropertyID,taxkey,District,nbhd,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_price
PropType,,,,,,,,,,,,,,
Commercial,44869081,823925205805,2024,1512628,384.5,454206.0,0.0,4393935.0,3804,277.0,2,1,8691495,341430294
Condominium,156562581,2832772831554,5634,4906768,1158.5,1744860.0,4402.0,1080728.0,887,1930.0,1281,328,456,240682999
Exempt,139550,2490008100,7,24910,0.0,0.0,0.0,0.0,0,0.0,0,0,0,225000
Lg Apartment,42157775,816838164621,1654,1606823,506.5,462497.0,0.0,1998916.0,2139,0.0,3,0,2529793,199274669
Manufacturing,850784,12040833100,44,37800,3.0,5981.0,0.0,109736.0,10,0.0,0,0,0,19090000
Residential,1032816137,20299573246383,46645,15767680,7789.5,11147033.0,47341.0,9041304.0,7524,24108.0,8972,1810,36488383,1139757361

In [33]:
group_by_frame.agg({'Sale_price':['mean','max','count','sum'],'Rooms':['mean','max','count','sum']})

                 Sale_price                                 Rooms              \
                       mean       max count         sum      mean   max count
PropType
Commercial     1.422626e+06  21850000   240   341430294  0.000000   0.0    77
Condominium    2.713450e+05   2625000   887   240682999  4.974011  14.0   885
Exempt         2.250000e+05    225000     1      225000       NaN   NaN     0
Lg Apartment   8.372885e+05  17400000   238   199274669       NaN   NaN     0
Manufacturing  3.181667e+06   8025000     6    19090000       NaN   NaN     0
Residential    1.973948e+05   2500000  5774  1139757361  8.246124  63.0  5741


                   sum
PropType
Commercial         0.0
Condominium     4402.0
Exempt             0.0
Lg Apartment       0.0
Manufacturing      0.0
Residential    47341.0

In [35]:
pd.options.display.max_rows = None
df.groupby(['PropType','Year_Built']).mean(numeric_only=True)[['Stories','Rooms','FinishedSqft','Units','Bdrms','Lotsize','Sale_price']]

                            Stories      Rooms   FinishedSqft       Units  \
PropType      Year_Built
Commercial    0.0          0.000000        NaN       0.000000    6.333333
              1870.0       3.000000   0.000000   10094.666667    5.333333
              1880.0       3.000000   0.000000    5770.000000    3.000000
              1881.0       3.000000        NaN   19898.000000    1.000000
              1883.0       2.000000   0.000000    2644.000000    3.000000
              1885.0       2.000000   0.000000    7079.666667    3.666667
              1886.0       2.000000   0.000000    4106.000000    3.000000
              1887.0       3.000000        NaN    2370.000000    7.000000
              1890.0       2.000000   0.000000    4193.428571    4.000000
              1891.0       2.500000        NaN   60069.000000   77.000000
              1892.0       2.000000   0.000000   19477.000000   12.000000
              1897.0       1.333333   0.000000    4939.666667    3.000000
              1899.0       1.500000   0.000000    2337.000000    2.000000
              1900.0       2.100000   0.000000    5701.800000    6.700000
              1904.0       7.000000        NaN   98035.000000   12.000000
              1905.0       2.000000   0.000000    3671.333333    3.666667
              1906.0       2.000000   0.000000    6322.000000    5.000000
              1907.0       1.500000   0.000000    2634.500000    2.500000
              1908.0       2.000000   0.000000   52760.000000    3.750000
              1909.0       2.000000   0.000000    2842.000000    2.000000
              1910.0       1.500000   0.000000    3115.500000    4.000000
              1911.0       2.000000   0.000000    3366.000000    4.000000
              1912.0       2.000000   0.000000    5494.000000    4.000000
              1913.0       2.000000   0.000000    3230.000000    3.500000
              1915.0       1.666667        NaN   16928.333333    3.333333
              1916.0       1.500000   0.000000    6943.000000    4.000000
              1919.0       2.000000   0.000000   12411.000000   11.000000
              1920.0       1.500000   0.000000    3641.500000    3.000000
              1921.0       2.000000   0.000000    5178.000000    3.000000
              1922.0       1.750000   0.000000    4431.500000    5.250000
              1923.0       2.000000   0.000000    9997.250000    7.500000
              1924.0       2.000000   0.000000    1992.000000    3.000000
              1925.0       2.090909   0.000000   18821.727273    3.545455
              1926.0       1.500000   0.000000    4916.250000    4.500000
              1927.0       1.666667   0.000000    5773.833333    5.000000
              1928.0       1.500000   0.000000    6433.000000    4.500000
              1929.0       1.500000        NaN   10379.000000    1.000000
              1930.0       1.750000   0.000000   21907.250000    4.750000
              1931.0       1.500000   0.000000    1618.000000    2.000000
              1934.0       1.500000   0.000000    5743.500000    4.500000
              1935.0       2.000000        NaN    7296.000000    2.000000
              1939.0       2.000000   0.000000    6412.000000    4.000000
              1940.0       1.000000   0.000000    4766.750000    3.000000
              1942.0       1.500000        NaN    9936.500000    2.000000
              1945.0       1.000000        NaN   35646.000000    3.000000
              1947.0       1.200000        NaN    8287.400000    2.000000
              1948.0       1.333333        NaN   40555.666667   20.333333
              1949.0       1.000000        NaN   16160.500000    1.000000
              1950.0       1.000000        NaN    5340.000000    1.000000
              1951.0       1.000000        NaN    4137.666667    1.666667
              1952.0       1.000000        NaN     782.000000    1.000000
              1953.0       1.000000        NaN    2534.500000    1.000000
              1954.0       1.666667   0.000000   15953.333333    4.666667
              1955.0       1.666667   0.000000    9868.000000    2.000000
              1957.0       1.500000        NaN   49222.750000    3.250000
              1958.0       1.333333        NaN   36007.000000   14.666667
              1959.0       1.000000        NaN    2617.333333    1.333333
              1960.0       1.500000        NaN   22920.000000    8.500000
              1961.0       1.666667   0.000000   11922.666667    3.666667
              1962.0       1.500000   0.000000    8136.000000    3.500000
              1963.0       1.000000        NaN   78259.000000    1.000000
              1964.0       1.333333        NaN   18255.666667   53.666667
              1965.0       1.333333        NaN   27674.666667    3.666667
              1966.0       1.000000        NaN    1778.000000    1.000000
              1967.0       1.200000        NaN    8739.600000   12.600000
              1968.0       1.000000        NaN   10528.500000    5.500000
              1969.0       2.000000        NaN   15605.000000    4.000000
              1970.0       1.000000        NaN   29557.000000   28.000000
              1971.0       1.000000        NaN    7200.000000    1.000000
              1972.0       3.333333        NaN   86839.333333  251.666667
              1974.0       1.000000        NaN   10530.000000    3.000000
              1975.0       1.000000        NaN    6113.000000    1.000000
              1976.0       1.000000        NaN   22715.500000    2.500000
              1978.0       2.000000        NaN    7444.000000    4.000000
              1980.0       1.000000        NaN    1703.000000    1.000000
              1981.0       1.000000        NaN    9020.000000    1.000000
              1982.0       1.000000        NaN   13662.500000   17.500000
              1983.0       4.666667        NaN   75648.000000  242.333333
              1984.0       1.000000   0.000000   26188.000000    2.500000
              1985.0       1.000000        NaN   15339.000000    2.000000
              1986.0       2.000000        NaN  107455.000000   59.500000
              1988.0       1.000000        NaN   10027.000000    1.000000
              1989.0       1.000000        NaN   17000.000000    1.000000
              1990.0       2.000000        NaN  129538.500000    4.500000
              1991.0       1.000000        NaN  139280.000000    2.000000
              1993.0            NaN        NaN   60841.000000   99.000000
              1994.0       1.000000        NaN   30000.000000    1.000000
              1995.0       1.000000        NaN    4428.000000    1.000000
              1997.0       1.000000        NaN    1219.000000    1.000000
              2001.0       1.000000        NaN    2039.000000    1.000000
              2002.0       1.000000        NaN    4198.000000    1.000000
              2003.0       1.000000        NaN    7338.500000   47.500000
              2004.0       1.000000        NaN    3871.000000    1.000000
              2005.0       1.000000        NaN  104365.000000    1.000000
              2006.0       1.000000        NaN   13717.333333    2.666667
              2007.0       0.500000        NaN   80022.500000    5.000000
              2008.0       2.000000        NaN   17961.000000    9.000000
              2010.0       1.000000   0.000000    4772.000000    3.000000
              2017.0       1.000000        NaN   64440.000000  389.000000
              2018.0       1.000000        NaN    2130.000000    1.000000
              2020.0       1.000000        NaN    4387.000000    1.000000
Condominium   1870.0       1.666667   4.666667    1257.000000    1.000000
              1875.0       1.000000   6.500000    1049.500000    1.000000
              1885.0       1.000000   3.000000     746.000000    1.000000
              1889.0       1.000000   4.454545    1396.909091    1.000000
              1890.0       2.333333   8.000000    1876.000000    1.000000
              1892.0       1.000000   7.800000    1164.800000    1.000000
              1893.0       1.156250   5.250000     965.312500    1.000000
              1894.0       1.000000   4.200000    1491.133333    1.000000
              1895.0       1.000000   3.375000    1077.625000    1.000000
              1897.0       1.400000   4.600000    1346.000000    1.000000
              1900.0       1.250000   3.750000     794.000000    1.000000
              1901.0       1.608696   4.739130    1018.782609    1.000000
              1903.0       1.000000   4.000000    2030.000000    1.000000
              1904.0       1.000000   3.200000     745.200000    1.000000
              1906.0       1.000000  10.500000    4150.000000    1.000000
              1907.0       1.000000   5.250000    1806.750000    1.000000
              1908.0       2.000000   5.000000    1223.000000    1.000000
              1911.0       1.000000   3.833333    1174.166667    1.000000
              1912.0       1.000000   5.666667    1807.000000    1.000000
              1913.0       2.000000   5.000000    1363.500000    1.000000
              1915.0            NaN   0.000000    1420.500000    1.000000
              1916.0       1.000000   5.666667    2157.000000    1.000000
              1917.0       1.000000   4.285714    1235.285714    1.000000
              1918.0       1.000000   4.800000    1133.200000    1.000000
              1920.0       1.500000   4.500000    1761.500000    1.000000
              1921.0       1.000000   1.750000    1121.500000    1.000000
              1922.0       1.166667   7.333333    1645.166667    1.000000
              1923.0       1.000000   7.000000    2317.000000    1.000000
              1924.0       2.000000   6.000000    1633.000000    1.000000
              1925.0       1.200000   5.600000    1195.600000    1.000000
              1926.0       1.600000   5.000000    1711.200000    1.000000
              1927.0       1.000000   3.000000     471.923077    1.000000
              1928.0       1.000000   3.000000     750.000000    1.000000
              1929.0       1.000000   4.818182     944.090909    1.000000
              1931.0       1.000000   4.000000     881.000000    1.000000
              1937.0       1.000000   5.000000    2307.000000    1.000000
              1945.0       1.000000   3.375000     998.875000    1.000000
              1958.0       1.000000   5.600000     779.000000    1.000000
              1960.0       2.000000  10.000000     937.000000    1.000000
              1961.0       1.000000   4.000000     716.000000    1.000000
              1962.0       2.000000   4.000000     907.000000    1.000000
              1963.0       1.000000   2.714286     530.000000    1.000000
              1965.0       1.000000   5.333333    1122.916667    1.000000
              1966.0       1.500000   4.000000     932.428571    1.000000
              1967.0       1.384615   4.384615     954.846154    1.000000
              1968.0       1.000000   4.000000    1057.100000    1.000000
              1969.0       1.000000   3.357143     612.642857    1.000000
              1970.0       2.000000   5.169811     994.301887    1.000000
              1971.0       1.304348   4.652174     941.434783    1.000000
              1972.0       1.037037   4.370370    1024.481481    1.000000
              1973.0       1.866667   5.822222    1221.333333    1.000000
              1974.0       1.383333   5.508197    1051.622951    1.000000
              1975.0       1.532258   5.677419    1133.290323    1.000000
              1978.0       1.375000   6.000000    1197.750000    1.000000
              1979.0       1.166667   4.583333     968.833333    1.000000
              1980.0       1.117647   5.235294    1019.588235    1.000000
              1981.0       1.000000   5.111111     942.666667    1.000000
              1982.0       1.000000   4.916667     946.000000    1.000000
              1983.0       1.214286   6.357143    1031.857143    1.000000
              1984.0       2.333333   4.333333    1299.333333    1.000000
              1986.0       1.833333   6.333333    1132.500000    1.000000
              1989.0       2.500000   5.000000    1700.000000    1.000000
              1990.0       1.000000   4.814815     916.407407    1.000000
              1992.0       1.250000   4.750000    1238.250000    1.000000
              1996.0       2.333333   5.333333    1547.333333    1.000000
              1997.0       2.000000   5.333333    1921.666667    1.000000
              1998.0       1.000000   6.000000    1308.166667    1.000000
              1999.0       1.666667   5.166667    1343.333333    1.000000
              2000.0       2.181818   4.272727    1632.272727    1.000000
              2001.0       2.107143   4.357143    1673.071429    1.000000
              2002.0       1.428571   5.285714    1763.523810    1.000000
              2003.0       1.333333   5.416667    1401.583333    1.000000
              2004.0       1.038462   5.520000    1498.076923    1.000000
              2005.0       1.685714   5.828571    1543.828571    1.000000
              2006.0       1.068627   6.000000    1484.509434    1.000000
              2007.0       1.192308   4.357143    1717.857143    1.000000
              2008.0       1.152174   5.304348    1447.956522    1.000000
              2009.0            NaN   0.000000    1930.083333    1.000000
              2010.0       1.000000   4.454545    1012.727273    1.000000
              2011.0            NaN   0.000000    3330.500000    1.000000
Lg Apartment  1880.0       1.250000        NaN    2852.000000    8.500000
              1889.0       2.000000        NaN    3198.000000    4.000000
              1890.0       2.000000        NaN    3659.750000    5.750000
              1891.0       3.000000        NaN    6307.000000    7.000000
              1892.0       2.000000        NaN    3285.000000    5.000000
              1893.0       2.000000        NaN    3375.000000    4.000000
              1894.0       2.000000        NaN    3146.500000    4.000000
              1895.0       2.400000        NaN   26832.400000   20.400000
              1896.0       2.000000        NaN    2879.000000    4.000000
              1898.0       2.000000        NaN    3338.000000    4.000000
              1900.0       2.125000        NaN    3312.500000    5.000000
              1901.0       2.000000        NaN    9591.000000   10.000000
              1903.0       2.000000        NaN    3128.500000    4.000000
              1904.0       2.000000        NaN    3244.000000    4.000000
              1905.0       2.000000        NaN    3803.000000    5.000000
              1906.0       2.000000        NaN    6147.000000    7.000000
              1907.0       2.000000        NaN    3624.000000    4.000000
              1908.0       2.000000        NaN    3598.600000    4.200000
              1909.0       2.333333        NaN    5804.000000    5.666667
              1910.0       2.000000        NaN    3605.800000    4.400000
              1911.0       2.666667        NaN    6672.333333    5.333333
              1912.0       2.500000        NaN    8524.250000    6.000000
              1913.0       3.000000        NaN    8250.000000    6.000000
              1914.0       2.000000        NaN    3597.000000    4.000000
              1915.0       2.000000        NaN    3840.000000    4.000000
              1916.0       3.000000        NaN   11191.000000   15.500000
              1918.0      14.000000        NaN  196753.000000  115.000000
              1920.0       2.000000        NaN    3066.000000    4.000000
              1923.0       3.000000        NaN   11712.000000   12.000000
              1925.0       2.250000        NaN    5293.500000    6.000000
              1926.0       2.200000        NaN    6806.600000    9.200000
              1927.0       3.000000        NaN   11556.333333   14.000000
              1928.0       2.200000        NaN    5450.200000    6.200000
              1929.0       2.000000        NaN    5404.000000    7.000000
              1930.0       2.000000        NaN    7073.000000    8.000000
              1931.0       2.000000        NaN    3484.000000    4.000000
              1941.0       2.000000        NaN    4174.000000    4.500000
              1945.0       2.000000        NaN    3302.000000    4.000000
              1947.0       2.000000        NaN    4971.600000    7.200000
              1948.0       2.000000        NaN    6219.000000    4.000000
              1950.0       1.500000        NaN    5446.500000   10.000000
              1951.0       2.000000        NaN    4070.000000    5.142857
              1952.0       1.875000        NaN    4703.000000    6.000000
              1953.0       1.666667        NaN    4593.333333    7.333333
              1954.0       2.000000        NaN    3269.000000    4.000000
              1955.0       2.222222        NaN    9408.555556   10.000000
              1956.0       2.000000        NaN    3484.500000    4.666667
              1957.0       1.900000        NaN    3823.100000    4.600000
              1958.0       2.000000        NaN    4300.444444    4.833333
              1959.0       2.000000        NaN    6359.047619    8.476190
              1960.0       2.000000        NaN    5152.000000    6.500000
              1961.0       2.000000        NaN    6206.888889    7.777778
              1962.0       2.000000        NaN    3664.000000    4.000000
              1963.0       2.000000        NaN    5396.750000    6.000000
              1964.0       2.000000        NaN   16549.333333   21.333333
              1965.0       2.000000        NaN    5974.500000    6.000000
              1966.0       2.000000        NaN    5452.666667    6.000000
              1967.0       2.000000        NaN    2892.000000    4.000000
              1970.0       2.000000        NaN    9237.500000   10.000000
              1971.0       2.000000        NaN    6027.666667    6.333333
              1972.0       2.000000        NaN    6928.000000    6.750000
              1976.0       2.000000        NaN    5168.000000    8.000000
              1978.0       2.000000        NaN   11410.000000   16.000000
              1979.0       2.000000        NaN   61204.000000   56.000000
              1980.0       2.000000        NaN    6480.000000    8.000000
              1994.0            NaN        NaN   35610.000000   32.000000
              2002.0       2.000000        NaN   46236.000000   45.000000
              2013.0       4.000000        NaN   29340.000000   34.000000
              2015.0            NaN        NaN   10179.000000   21.000000
              2016.0       4.000000        NaN   46893.500000   53.000000
              2017.0       5.000000        NaN   91454.000000   70.000000
              2018.0       5.000000        NaN   61940.000000   62.000000
Manufacturing 1978.0       1.000000        NaN   20600.000000    6.000000
              1989.0       1.000000        NaN   20860.000000    1.000000
              2014.0       1.000000        NaN   68276.000000    2.000000
Residential   0.0          0.000000        NaN            NaN    0.000000
              1836.0       2.000000  18.000000    2190.000000    1.000000
              1843.0       1.000000   7.000000    1372.000000    1.000000
              1855.0       2.000000   6.000000    1846.000000    1.000000
              1860.0       1.250000  10.500000    2066.000000    2.000000
              1861.0       2.000000  14.000000    1827.500000    1.000000
              1865.0       2.000000   7.000000    1742.333333    1.333333
              1868.0       1.000000   4.000000    1674.000000    1.000000
              1869.0       2.000000   7.000000    1758.000000    1.000000
              1870.0       1.611111   8.666667    1623.222222    1.777778
              1873.0       1.750000  11.500000    1449.000000    1.500000
              1874.0       1.000000  12.000000    1797.000000    2.000000

In [45]:
df.groupby('PropType').describe()

              PropertyID                                                    \
                   count           mean           std       min        25%
PropType
Commercial         240.0  186954.504167  49547.814209   98464.0  145414.75
Condominium        887.0  176507.983089  45451.476912   98696.0  143634.00
Exempt               1.0  139550.000000           NaN  139550.0  139550.00
Lg Apartment       238.0  177133.508403  45688.632981  102594.0  133479.75
Manufacturing        6.0  141797.333333  52067.762036   98461.0  101231.75
Residential       5774.0  178873.594908  48347.007218   98508.0  135291.00

                                              taxkey                ...  \
                    50%        75%       max   count          mean  ...
PropType                                                            ...
Commercial     198640.5  219992.25  265996.0   240.0  3.433022e+09  ...
Condominium    190775.0  200506.00  266017.0   887.0  3.193656e+09  ...
Exempt         139550.0  139550.00  139550.0     1.0  2.490008e+09  ...
Lg Apartment   175550.0  214319.75  265945.0   238.0  3.432093e+09  ...
Manufacturing  119102.5  188825.25  206777.0     6.0  2.006806e+09  ...
Residential    172212.5  225532.25  266040.0  5774.0  3.515686e+09  ...

                Lotsize            Sale_price                              \
                    75%        max      count          mean           std
PropType
Commercial     21948.00   835916.0      240.0  1.422626e+06  3.237789e+06
Condominium        1.00        1.0      887.0  2.713450e+05  2.685096e+05
Exempt             0.00        0.0        1.0  2.250000e+05           NaN
Lg Apartment   10593.75   157732.0      238.0  8.372885e+05  2.109057e+06
Manufacturing      0.00        0.0        6.0  3.181667e+06  3.554379e+06
Residential     6850.00  1341648.0     5774.0  1.973948e+05  1.134750e+05


                    min       25%        50%        75%         max
PropType
Commercial      25000.0  215000.0   417500.0  1012500.0  21850000.0
Condominium     25000.0  106500.0   206000.0   344000.0   2625000.0
Exempt         225000.0  225000.0   225000.0   225000.0    225000.0
Lg Apartment   120000.0  266250.0   359216.0   578750.0  17400000.0
Manufacturing  320000.0  852500.0  1237500.0  5968750.0   8025000.0
Residential      4000.0  131000.0   186950.0   245000.0   2500000.0

[6 rows x 112 columns]

In [18]:
%history
#run to see command history

print(plt.style.available)
#plt.style.use('fivethirtyeight')
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy as scipy
df=pd.read_csv('2022-property-sales-data-1.csv')
pd.set_option('display.max.rows', None) #Show all columns in header
df.head()
df.info()
df.shape
specific_extwalls=['Wood','Brick']
df[df['Extwall'].isin(specific_extwalls)][0:15]
df = df.reset_index()
df1=df.set_index('PropertyID')
df1.head()
#Find duplicate PropertyID
df[df1.index.duplicated()].head(10)
df2=df.set_index(['PropertyID','Sale_price'])
df2.head(10)
df2.reset_index(inplace=True)
df2.head()
group_by_frame=df.groupby('PropType')
group_by_frame.mean(numeric_only=True)#uses groupby.mean()
#print(plt.style.available)
#plt.style.use('fivethirtyeight')
print(plt.style.available)
#plt.style.use('fivethirtyeight')
print(plt.style.available)
plt.style.use('fivethirtyeight')
%history

In [17]:
print(plt.style.available)
plt.style.use('fivethirtyeight')

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']

In [36]:
#Continued on Part 2